# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\github\tools-box\tools-box\pythonGUI\Port.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Port(object):
    def setupUi(self, Port):
        Port.setObjectName("Port")
        Port.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Port)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_in = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_in.setGeometry(QtCore.QRect(21, 99, 761, 24))
        self.lineEdit_in.setObjectName("lineEdit_in")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 30, 51, 71))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 420, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 140, 41, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(23, 170, 761, 201))
        self.textEdit.setObjectName("textEdit")
        Port.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Port)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Port.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Port)
        self.statusbar.setObjectName("statusbar")
        Port.setStatusBar(self.statusbar)

        self.retranslateUi(Port)
        QtCore.QMetaObject.connectSlotsByName(Port)

    def retranslateUi(self, Port):
        _translate = QtCore.QCoreApplication.translate
        Port.setWindowTitle(_translate("Port", "MainWindow"))
        self.label.setText(_translate("Port", "目标IP"))
        self.pushButton.setText(_translate("Port", "扫描"))
        self.label_2.setText(_translate("Port", "输出"))
