# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\github\tools-box\tools-box\pythonGUI\TranQR.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tran(object):
    def setupUi(self, Tran):
        Tran.setObjectName("Tran")
        Tran.setEnabled(True)
        Tran.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(Tran)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(220, 80, 541, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 160, 541, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 167, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        Tran.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        Tran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tran)
        self.statusbar.setObjectName("statusbar")
        Tran.setStatusBar(self.statusbar)

        self.retranslateUi(Tran)
        QtCore.QMetaObject.connectSlotsByName(Tran)

    def retranslateUi(self, Tran):
        _translate = QtCore.QCoreApplication.translate
        Tran.setWindowTitle(_translate("Tran", "MainWindow"))
        self.pushButton.setText(_translate("Tran", "转换"))
        self.label.setText(_translate("Tran", "输入待转换的字符串"))
        self.label_2.setText(_translate("Tran", "输入生成图片的存储路径"))
