# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\github\tools-box\tools-box\pythonGUI\Tran - 副本.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tran(object):
    def setupUi(self, Tran):
        Tran.setObjectName("Tran")
        Tran.setEnabled(True)
        Tran.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(Tran)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(220, 80, 311, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 160, 311, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 60, 107, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(90, 230, 101, 47))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        Tran.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tran)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        Tran.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tran)
        self.statusbar.setObjectName("statusbar")
        Tran.setStatusBar(self.statusbar)

        self.retranslateUi(Tran)
        self.checkBox.toggled['bool'].connect(self.lineEdit.setEnabled)
        self.checkBox.toggled['bool'].connect(self.lineEdit_2.setEnabled)
        self.checkBox.toggled['bool'].connect(self.checkBox_2.setDisabled)
        self.checkBox_2.toggled['bool'].connect(self.lineEdit.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.lineEdit_2.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.checkBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Tran)

    def retranslateUi(self, Tran):
        _translate = QtCore.QCoreApplication.translate
        Tran.setWindowTitle(_translate("Tran", "MainWindow"))
        self.pushButton.setText(_translate("Tran", "转换"))
        self.label.setText(_translate("Tran", "待转换文件路径"))
        self.label_2.setText(_translate("Tran", "转换后文件名"))
        self.checkBox.setText(_translate("Tran", "CSV->xlsx"))
        self.checkBox_2.setText(_translate("Tran", "xlsx->CSV"))
