# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\github\tools-box\tools-box\pythonGUI\Tran_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tran_ui(object):
    def setupUi(self, Tran_ui):
        Tran_ui.setObjectName("Tran_ui")
        Tran_ui.resize(792, 600)
        self.centralwidget = QtWidgets.QWidget(Tran_ui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 221, 41))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(340, 80, 95, 391))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        Tran_ui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tran_ui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 26))
        self.menubar.setObjectName("menubar")
        Tran_ui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tran_ui)
        self.statusbar.setObjectName("statusbar")
        Tran_ui.setStatusBar(self.statusbar)

        self.retranslateUi(Tran_ui)
        QtCore.QMetaObject.connectSlotsByName(Tran_ui)

    def retranslateUi(self, Tran_ui):
        _translate = QtCore.QCoreApplication.translate
        Tran_ui.setWindowTitle(_translate("Tran_ui", "MainWindow"))
        self.label.setText(_translate("Tran_ui", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">CSV-xlsx格式转换工具</span></p></body></html>"))
        self.pushButton.setText(_translate("Tran_ui", "文件转换"))
        self.pushButton_2.setText(_translate("Tran_ui", "文件读取"))
        self.pushButton_3.setText(_translate("Tran_ui", "退出程序"))
