# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\github\tools-box\tools-box\pythonGUI\Zhuanhuan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zhuanhuan(object):
    def setupUi(self, zhuanhuan):
        zhuanhuan.setObjectName("zhuanhuan")
        zhuanhuan.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(zhuanhuan)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 761, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(260, 300, 211, 71))
        self.label_output.setObjectName("label_output")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, -10, 241, 71))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 140, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(237, 230, 281, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        zhuanhuan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(zhuanhuan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        zhuanhuan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(zhuanhuan)
        self.statusbar.setObjectName("statusbar")
        zhuanhuan.setStatusBar(self.statusbar)

        self.retranslateUi(zhuanhuan)
        QtCore.QMetaObject.connectSlotsByName(zhuanhuan)

    def retranslateUi(self, zhuanhuan):
        _translate = QtCore.QCoreApplication.translate
        zhuanhuan.setWindowTitle(_translate("zhuanhuan", "MainWindow"))
        self.label_output.setText(_translate("zhuanhuan", "   "))
        self.label.setText(_translate("zhuanhuan", "请输入想要转换的图片的路径"))
        self.pushButton.setText(_translate("zhuanhuan", "转换"))
